CRUISE/CRUISE/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from cruiseWeb import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cruise/', include('cruiseWeb.urls')),
]

CRUISE/cruiseWeb/urls.py
from django.conf.urls import url
from cruiseWeb import views

app_name = 'cruiseWeb'

urlpatterns=[
    url(r'^$', views.index, name='index'),
    url(r'^project', views.projectDescr, name='projectDescription'),
    url(r'^aboutUs', views.aboutUs, name = 'aboutUs'),
    url(r'^survey', views.gtSurvey, name = 'gtSurvey'),
    url(r'^cruiseMock', views.cruiseDemo, name='cruiseDemo'),
    url(r'^technical', views.technicalElement, name='technical'),
    url(r'^thanks', views.thankyou, name='thankyou'),
]

CRUISE/cruiseWeb/models.py
from django.db import models

# Create your models here.
class Tweet(models.Model):
    tweetText = models.CharField(max_length = 264)
    createdDate = models.DateTimeField()
    completedCount = models.IntegerField(default=0)
    # completed = models.BooleanField(default = False)

    def __str__(self):
        dateString = "Created at:" + str(self.createdDate)
        tweetString = " Text: " + self.tweetText
        return  self.tweetText

class ObtainedDataNER(models.Model):
    tweet = models.ForeignKey(Tweet)
    tLocation = models.CharField(max_length= 300)
    tState = models.CharField(max_length = 200)

    def __str__(self):
        tLocationList = tLocation.split(',')
        tStateList = tState.split(',')
        totalList = tLocationList + tStateList
        return totalList

class ObtainedDataCA(models.Model):
    dataOrigin = models.ForeignKey(ObtainedDataNER)
    locationOne = models.CharField(max_length= 100)
    locationTwo = models.CharField(max_length= 100)
    state = models.CharField(max_length= 50)

    def __str__(self):
        trafficString = self.locationOne +','+self.locationTwo+" is "+self.state
        return trafficString

CRUISE/cruiseWeb/forms.py
from django import forms
from cruiseWeb.models import Tweet, ObtainedDataNER


class NewNerForm(forms.ModelForm):

    class Meta():
        model = ObtainedDataNER
        fields = ['tLocation','tState']
        widgets = {
            'tLocation': forms.TextInput(attrs={'class': 'form-control'}),
            'tState': forms.TextInput(attrs={'class': 'form-control'})
        }
        labels = {
            "tLocation": "Location List",
            "tState": "State List"
        }

    # def __init__ (self, text, *args, **kwargs):
    #     self.text = text
    #     super (NewNerForm, self).__init__ (*args, **kwargs)

    # def __init__ (self, tweet, *args, **kwargs):
    #     self.tweet = tweet
    #     super (NewNerForm, self).__init__ (*args, **kwargs)

    # location = forms.CharField(widget=forms.Textarea)
    # state = forms.CharField()

# class testForm(forms.ModelForm):
#     class Meta():
#         model = Tweet
#         fields = ['completed']
#         widgets = {'completed': forms.HiddenInput()}

CRUISE/cruiseWeb/views.py
from django.shortcuts import render
from cruiseWeb import forms
from cruiseWeb.models import Tweet, ObtainedDataNER
from django.forms.formsets import formset_factory
from django.db.models import Avg, Min, Max
# Create your views here.
def index(request):
    return render(request, 'cruiseWeb/index.html')

def aboutUs(request):
    return render(request, 'cruiseWeb/aboutUs.html')

def projectDescr(request):
    return render(request, 'cruiseWeb/projdesc.html')

def cruiseDemo(request):

    return render(request, 'cruiseWeb/demo.html')

def technicalElement(request):
    return render(request, 'cruiseWeb/techManual.html')

def gtSurvey(request):
    allTweets =Tweet.objects.all()
    minDict = allTweets.aggregate(Min('completedCount'))
    minVal = minDict['completedCount__min']
    print("LOWEST UNFINISHED :"+ str(minVal))
    tweet_items = Tweet.objects.filter(completedCount=minVal)[:10]
    # print(tweet_items)
    # for ea in tweet_items:
    #     print(ea.id)
    qForms = formset_factory(forms.NewNerForm, extra=len(tweet_items))

    if request.method == 'POST':
        qForms = qForms(request.POST)
        if qForms.is_valid():

            for num, form in enumerate(qForms):
                # print(num)
                if form.is_valid():
                    obj = form.save(commit = False)
                    # print(tweet_items[num])
                    # print("ID: "+ str(tweet_items[num].tweetText))
                    # print("ID: "+ str(tweet_items[num].id))
                    obj.tweet = tweet_items[num]
                    obj.save()

                    temp = tweet_items[num]
                    temp.completedCount = temp.completedCount+1
                    # print(temp.completed)
                    temp.save()

                    # tweet_items = Tweet.objects.filter(completed=False)[:3]
                    # qForms = formset_factory(forms.NewNerForm, extra=3)
            return thankyou(request)
        # do nth

    return render(request, 'cruiseWeb/gtSurvey.html', {'formset':qForms(), 'tweetset':tweet_items})
    # tweet = Tweet.objects.filter(completed=False)[:1]
    # tweet = tweet[0]
    #
    # # form = forms.NewNerForm(tweet)
    # form = forms.NewNerForm()
    # dataGroup = {'text' : tweet.tweetText, 'form':form}
    #
    # if request.method =="POST":
    #     form = forms.NewNerForm(request.POST)
    #     if form.is_valid():
    #         obj = form.save(commit = False)
    #         obj.tweet = tweet
    #         obj.save()
    #         tweet.completed = True
    #         tweet.save()
    #         # form.save(commit = True)
    #         print("INPUT GET!")
    #         print("LOCATION: "+ form.cleaned_data['tLocation'])
    #         print("STATE: "+ form.cleaned_data['tState'])
    #
    #         tweet = Tweet.objects.filter(completed=False)[:1]
    #         tweet = tweet[0]
    #         form = forms.NewNerForm()
    #         dataGroup = {'text' : tweet.tweetText, 'form':form}
    #
    #     else:
    #         print("UH OH! Something is wrong!")
    #
    # return render(request, 'cruiseWeb/gtSurvey.html', context = dataGroup)

def thankyou(request):

    return render(request, 'cruiseWeb/thankyou.html')

CRUISE/templates/cruiseWeb/aboutUs.html
<!DOCTYPE html>
{% extends "cruiseWeb/base.html" %}
{% load staticfiles %}
  {% block head_block %}
  <title>CRUISE: AboutUs</title>
  <link href="https://fonts.googleapis.com/css?family=Chewy|Permanent+Marker" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
  {% endblock %}
  {% block body_block %}
  <div class="divBlock abUsblock1">
    <div class="container">

      <div class="row">
        <div class="col-lg-8">
          <h1 class="pageMainLabel">Simple facts about us</h1>
          <br>
          <p class="descriptionText">We are a group of researchers in Multimedia University Cyberjaya. Our group consists of 3 core personals:
            The project leader, Dr Ian Tan, The Supervisor, Dr Bhawani and The student, Lim Cheng Yang. This project started
          at Q4 of 2015 and the project / research revolves mainly on Data Mining and Natural Language Processing (NLP).</p>
        </div>
        <div class="col-lg-4">
          <img id="mmuLogo" src="{% static "images/mmuLogo.png"%}" alt="">
        </div>
      </div>
    </div>
  </div>

  <div class="divBlock abUsblock2">
    <div class="container">
      <div class="row">
        <h1 class="name">Dr. Ian Tan</h1>
        <div class="col-lg-8">
          <div class="">
            <h2 class="subname">Project Leader</h2>
            <p class="descriptionText">Ian K. T. Tan received his PhD in Information Technology from Multimedia University, Malaysia, his Master of Science in Parallel Computers and Computation from University of Warwick, United Kingdom and his Bachelor of Engineering in Information Systems Engineering from Imperial College London, United Kingdom in 2016, 1993 and 1992 respectively.
              Prior to his current position as Lecturer at Multimedia University, Cyberjaya; he has worked in the area of microprocessor manufacturing, enterprise UNIX servers, storage management to VoIP technologies. His area of research is in operating systems scheduling for multicore processors, data transfer optimization across wide area networks and multimedia processing and analytics.
              Dr Tan is an Associate Board Member of Teradata University Network and an Associate of the City and Guilds Institute.  He is Novell Certified Linux Administrator (NCLA), Novell Certified Linux Professional (NCLP)
            </p>
          </div>
        </div>
        <div class="col-lg-4">
          <img src="{% static "images/ian.png"%}" alt="Picture of our Handsome Ian Tan">
        </div>
        <br>
      </div>
      <br>
    </div>
  </div>

  <div class="divBlock abUsblock3">
    <div class="container">
      <div class="row">
        <h1 class="name">Dr. Bhawani</h1>
        <div class="col-lg-8">
          <div class="">
            <h2 class="subname">Supervisor</h2>
            <p class="descriptionText">Dr. Bhawani Selvaretnam is a lecturer at the Faculty of Computing and Informatics, Multimedia University. She obtained her doctorate in Information Technology from Monash University in 2013 and a Master of Science in Information Technology from the Malaysia University of Science and Technology in 2005.  She received her Bachelor of Computer Science (Hons) degree from University Malaya, Malaysia in 2003. She has 11 years of teaching experience on subjects such as computer networks, digital systems, research methods, data science etc. She also actively conducts training in the field of Data Science for various government and corporate agencies. She is a member of two research centers i.e.  Center of Web Engineering and the Data Science Institute at Multimedia University. Her research interests are in the area of natural language processing, information retrieval and social media analytics. She is currently working on research projects in the area of text analytics inclusive of social media analytics, sentiment analysis and search engine optimization. These projects are funded by government and private entities such as TM R&D, CREST and Plentisoft Sdn. Bhd
            </p>
          </div>
        </div>
        <div class="col-lg-4">
          <img src="{% static "images/ian.png"%}" alt="Picture of our Handsome Ian Tan">
        </div>
      </div>
      <br>
    </div>
  </div>

  <div class="divBlock abUsblock4">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="">
            <h1 class="name">Lim Cheng Yang</h1>
            <h2 class="subname">Student / Developer</h2>
            <p class="descriptionText">Lim Cheng Yang received his Bachelor’s Degree of Computer Science specialization in Software Engineering from Multimedia University, Malaysia in 2015. He is currently pursuing Masters of Science (Information Technology) in Multimedia University, Malaysia. His research areas include Data Analytics and Natural Language Processing.
            </p>
          </div>
        </div>
        <div class="col-lg-4">
          <img src="{% static "images/ian.png"%}" alt="Picture of our Handsome Ian Tan">
        </div>
      </div>
    </div>
  </div>

  <div class="divBlock abUsblock5">
    <div class="container">
      <h1 class="name">Funders</h1>
      <div class="row">
        <div class="col-lg-8">
          <div class="">
            <h2 class="subname">CREST</h2>
            <p class="descriptionText">This article and the findings are based on work supported by the Collaborative Research in Engineering, Science & Technology (CREST) Funding under grant number P04C3-14. Any opinions given, findings, and conclusions or recommendations that is stated in this article are those of authors and do not necessarily reflect those of CREST.</p>
          </div>
        </div>
        <div class="col-lg-4">
          <img id="crestLogo" src="{% static "images/CREST_Logo.png"%}" alt="Picture of our Handsome Ian Tan">
        </div>
        <br>
      </div>
    </div>
  </div>

  {% endblock %}

CRUISE/templates/cruiseWeb/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    {% block head_block %}
    {% endblock %}
    <link rel="SHORTCUT ICON" href="{% static "images/logo.ico"%}" type="image/x-icon" />
    <link rel="stylesheet" href="{% static "cruiseWeb/css/common.css" %}">
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet"/>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'cruiseWeb:index'%}">CRUISE</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class = "nav navbar-nav">
            <li><a class="navbar-link" href="{%url 'cruiseWeb:projectDescription'%}">Project</a></li>
            <li><a class="navbar-link" href="{%url 'cruiseWeb:technical'%}">Tech</a></li>
            <li><a class="navbar-link" href="{%url 'cruiseWeb:cruiseDemo'%}">Demo</a></li>
            <li><a class="navbar-link" href="{%url 'cruiseWeb:aboutUs'%}">About Us</a></li>
            <li><a class="navbar-link" href="{%url 'cruiseWeb:gtSurvey'%}">Survey</a></li>
          </ul>
        </div>
      </div>
    </nav>

      <!-- <h1 class="dead"> Test CSS </h1> -->
    {% block body_block %}
    <!-- Anything outside this will be inherited if you extend -->
    {% endblock %}

    <div class="footer">
      <p class="footerText classCenter">This webpage is developed with Django by CYLim.</p>
    </div>

    <script
  src="https://code.jquery.com/jquery-3.2.1.js"
  integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
  crossorigin="anonymous"></script>
  <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </body>
</html>

CRUISE/templates/cruiseWeb/demo.html
<!DOCTYPE html>
{% extends "cruiseWeb/base.html" %}
{% load staticfiles %}
  {% block head_block %}
  <title>CRUISE: Demo</title>
  {% endblock %}
  {% block body_block %}
  <div class="divBlock projBlock4">
    <div class="container">
      <h1>Welcome to Cruise Demo Page</h1>

        <h1>Coming soon !</h1>

        <h1>Enjoy this dancing banana at the mean time !</h1>
        <img src="{% static "images/banana.gif"%}" alt="">

    </div>
  </div>



  {% endblock %}

CRUISE/templates/cruiseWeb/gtSurvey.html
<!DOCTYPE html>
{% extends "cruiseWeb/base.html" %}
{% load staticfiles %}
{% load temp_extra %}
  {% block head_block %}
  <title>CRUISE: Survey</title>
  {% endblock %}


  {% block body_block %}
  <div class="information">
    <div class="container">
      <h2>Please help in annotating our ground truths!</h2>
    </div>
  </div>

  <div class="container">
    <!-- <h1>Testing of formsets </h1> -->
    <form method="POST">
      {{ formset.management_form}}
      {% for form in formset%}
        <h3 class="tweet">{{ tweetset|index:forloop.counter0 }}</h3>
        {{form.as_p}}
        <hr>
      {% endfor %}
      {% csrf_token %}
      <input type="submit" class="btn btn-primary" id="rightButtton" value="Submit">
    </form>
  </div>



  {% endblock %}

CRUISE/templates/cruiseWeb/index.html
<!DOCTYPE html>
{% extends "cruiseWeb/base.html" %}
{% load staticfiles %}
  {% block head_block %}
  <title>CRUISE: Home</title>
  <link href="https://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet"/>
  {% endblock %}
  {% block body_block %}
  <div class="mainpageBody">
    <div class="container">
      <div class="jumbotron" id="centerdiv">
        <div class="row">
          <div class="col-lg-6">
            <h1 class="dead">CRUISE</h1>
            <hr>
            <h3>A Twitter-Sourced Traffic Reporting System</h3>
          </div>
          <div class="col-lg-6">
            <img class="media-object right" src="{% static "images/phone.png"%}">
          </div>

        </div>
      </div>
      </div>
  </div>


  {% endblock %}

CRUISE/templates/cruiseWeb/projdesc.html
<!DOCTYPE html>
{% extends "cruiseWeb/base.html" %}
{% load staticfiles %}
{% load temp_extra %}
  {% block head_block %}
  <title>CRUISE: Project</title>
  {% endblock %}
  {% block body_block %}

  <div class="divBlock projBlock2">
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <img src="{% static "images/logo.png"%}" alt="">
        </div>
        <div class="col-lg-8 testCenter">
          <h1>What is it?</h1>
          <p class="descriptionText">CRUISE is a traffic reporting system that gathers information through crowdsourcing. CRUISE crawls traffic
          related data from Twitter and processes it into useful data which could be useful to the users.</p>
        </div>
      </div>
      <br>
    </div>
  </div>

  <div class="divBlock projBlock2">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <h1>Motivation</h1>
          <p class="descriptionText">Enclosed vehicles have applications like Waze, Google Maps, which allows them can avoid traffic congestion.
            Howeverm, semi-enclosed vehicles doesn’t have such luxury. Using these apps will rob them of their attention.
            Thus this project conveys a way to transmit the traffic data to the motorcyclists through crowd-sourcing through Twiter
            or the app users (PHASE 2).</p>
        </div>
        <div class="col-lg-4">
          <img src="{% static "images/TwitterLogo.png"%}" alt="">
        </div>
      </div>
      <br>
    </div>
  </div>

  <div class="divBlock projBlock2">
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <img src="{% static "images/question.jpeg"%}" alt="">
        </div>
        <div class="col-lg-8 justLeft">
          <h1>How it works</h1>
          <p class="descriptionText">CRUISE crawls and filters the traffic related tweets from Twitter. The tweets are then passed on to undergo a
          series of NLP processes to obtain the traffic location and the traffic states. After that, contextual analysis
          is carried out to relate the relationships between the locations and traffic state. Reconciliation is then
          carried out to conclude the actual traffic states of respective locations and then stored into the database.</p>
        </div>
        <br>
      </div>
    </div>
  </div>

  <div class="divBlock projBlock2">
    <div class="container">
      <div class="row">
        <h1>How to obtain it</h1>
        <div class="col-lg-8">
          <p class="descriptionText">It's easy ! Just install the CRUISE app and it will report the traffic conditions around* you (depending on
            the sensitivity set). Currently the app is on closed beta, it will be available for public soon !</p>
        </div>
        <div class="col-lg-4">
          <img src="{% static "images/comingSoon.png"%}" alt="">
        </div>
      </div>
      <br>
    </div>
  </div>

  <div class="divBlock projBlock2">
    <div class="container">
      <h1>Programming Languages Involved</h1>

      <div class="row">
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <img class="smallThumb" src="{%static "images/python.png"%}" alt="...">
            <div class="caption">
              <h3 class="label_text">Python</h3>
              <p class="classCenter"><a href="https://www.python.org/" class="btn btn-primary" role="button">Visit Page</a></p>
            </div>
          </div>
        </div>

        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <img class="smallThumb" src="{%static "images/django.png"%}" alt="...">
            <div class="caption">
              <h3 class="label_text">Django</h3>
              <p class="classCenter"><a href="https://www.djangoproject.com/" class="btn btn-primary" role="button">Visit Page</a></p>
            </div>
          </div>
        </div>

        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <img class="smallThumb" src="{%static "images/android.jpg"%}" alt="...">
            <div class="caption">
              <h3 class="label_text">Android</h3>
              <p class="classCenter"><a href="https://www.android.com/" class="btn btn-primary" role="button">Visit Page</a></p>
            </div>
          </div>
        </div>
      </div>
  </div>


  {% endblock %}

CRUISE/templates/cruiseWeb/techManual.html
<!DOCTYPE html>
{% extends "cruiseWeb/base.html" %}
{% load staticfiles %}
  {% block head_block %}
  <title>CRUISE: Tech</title>
  {% endblock %}
  {% block body_block %}

  <div class="divBlock block1">
    <div class="container">
      <h1>Technologies Behind</h1>
      <h2>Overall Architecture</h2>
      <img class="bigImage classCenter" src="{% static "/images/overallArc.jpg" %}" alt="">
      <br>
      <p>There are five main components in the system which includes:</p>
      <ul>
        <li><b>Crawler</b>: Twitter API crawler to crawl the traffic data</li>
        <li><b>NLP</b>: Natural Language Processes where the data is being extracted and interpreted</li>
        <li><b>Phone/End node</b>: An android phone that runs the software solution</li>
        <li><b>User</b>: Participant of the system</li>
        <li><b>Web Service</b>: Interacts with the database and the phone</li>
      </ul>

    </div>
  </div>


  <div class="divBlock block2">
    <div class="container">
      <h1>NLP</h1>
      <h2>Named Entity Recognition</h2>
      <img src="{% static "images/NER.gif" %}" alt="">
      <br>
      <p class="descriptionText">Named Entity Recognition (NLP) is the process of extracting named entity (which commonly are Nouns)
      from the text. The NER system in tweaked to add the extra ability in extraction of traffic state.</p>
      <br>
    </div>
  </div>



  <div class="divBlock block3">
    <div class="container">
      <h2>Contextual Analysis</h2>
      <img src="{% static "images/CA.gif" %}" alt="">
      <br>
      <p class="descriptionText">Contextual Analysis is the process to understand the text in sentence level. In this project,
      contextual analysis is cruitial in relating the relationship of the extracted data for analysis.</p>
      <br>
    </div>
  </div>

  <div class="divBlock block4">
    <div class="container">
      <h2>Reconciliation</h2>
      <img src="{% static "images/recon.gif" %}" alt="">
      <p class="descriptionText">There is possibilities that the extracted data contradicts with each other. This is where the
      reconciliation takes place. This process will weight the data and make a conclusion for the traffic
      state for the respective data.</p>
      <br>
    </div>
  </div>

  {% endblock %}

CRUISE/templates/cruiseWeb/thankyou.html
<!DOCTYPE html>
{% extends "cruiseWeb/base.html" %}
{% load staticfiles %}
  {% block head_block %}
  <title>CRUISE: Demo</title>

  <script type="text/javascript">
        setTimeout(function() {
            window.location.href = "/cruise/";
        }, 5000);
    </script>
  {% endblock %}
  
  {% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Thanks for the response !</h1>
      <h3>Feel free to fill up more ground truths~</h3>
      <img src="{% static "images/thankCat.gif"%}" alt="">
    </div>
  </div>

  {% endblock %}